services:
  kafka:
    image: bitnami/kafka:${KAFKA_VERSION}
    hostname: kafka
    container_name: kafka
    healthcheck:
      test: kafka-topics.sh --bootstrap-server kafka:9092 --list
      start_period: 30s
      start_interval: 5s
      #      interval: 30s      # waiting for https://github.com/docker/compose/issues/10830
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "9094:9094"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=Cl1akjnHRoG9df2FiSicNg
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://${JAWS_EXTERNAL_HOSTNAME}:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LOG_CLEANER_MIN_CLEANABLE_RATIO=0.1
      - KAFKA_CFG_LOG_CLEANER_MAX_COMPACTION_LAG_MS=600000
      - KAFKA_CFG_LOG_CLEANER_MIN_COMPACTION_LAG_MS=300000
      - KAFKA_CFG_LOG_ROLL_MS=300000
      - KAFKA_CFG_LOG_MESSAGE_TIMESTAMP_TYPE=LogAppendTime

  registry:
    image: bitnami/schema-registry:${REGISTRY_VERSION}
    hostname: registry
    container_name: registry
    healthcheck:
      test: schema-registry-run-class io.confluent.kafka.schemaregistry.tools.SchemaRegistryPerformance http://localhost:8081 healthcheck 1 1 JSON
      start_period: 30s
      start_interval: 5s
      #      interval: 30s      # waiting for https://github.com/docker/compose/issues/10830
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:9092

  cli:
    image: jeffersonlab/jaws-libp:${CLI_ADMIN_VERSION}
    tty: true
    stdin_open: true
    hostname: cli
    container_name: cli
    healthcheck:
      test: test $(list_schemas | wc -l) -gt 20
      start_period: 30s
      start_interval: 5s
      #      interval: 30s      # waiting for https://github.com/docker/compose/issues/10830
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      registry:
        condition: service_healthy
    environment:
      - TZ=America/New_York
      - BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY=http://registry:8081
      - LOGLEVEL=INFO

  processor:
    image: jeffersonlab/jaws-effective-processor:${PROCESSOR_VERSION}
    hostname: processor
    container_name: processor
    healthcheck:
      test: test $(ps | grep jaws | wc -l) -gt 1
      start_period: 30s
      start_interval: 5s
      #      interval: 30s      # waiting for https://github.com/docker/compose/issues/10830
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      cli:
        condition: service_healthy
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY=http://registry:8081