services:
  kafka:
    image: bitnami/kafka:3.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=Cl1akjnHRoG9df2FiSicNg
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LOG_CLEANER_MIN_CLEANABLE_RATIO=0.1
      - KAFKA_CFG_LOG_CLEANER_MAX_COMPACTION_LAG_MS=600000
      - KAFKA_CFG_LOG_CLEANER_MIN_COMPACTION_LAG_MS=300000
      - KAFKA_CFG_LOG_ROLL_MS=300000
    healthcheck:
      test: kafka-topics.sh --bootstrap-server kafka:9092 --list
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5

  registry:
    image: bitnami/schema-registry:7.4
    hostname: registry
    container_name: registry
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:9092