services:
  kafka:
    extends:
      file: deps.yml
      service: kafka

  registry:
    extends:
      file: deps.yml
      service: registry

  jaws-libp:
    image: jeffersonlab/jaws-libp:4.6.3
    tty: true
    stdin_open: true
    hostname: jaws-libp
    container_name: jaws-libp
    depends_on:
      - kafka
      - registry
    environment:
      TZ: "America/New_York"
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"
      LOGLEVEL: "INFO"
      ALARM_LOCATIONS: https://raw.githubusercontent.com/JeffersonLab/alarms/main/locations
      ALARM_CATEGORIES: https://raw.githubusercontent.com/JeffersonLab/alarms/main/categories
      ALARM_CLASSES: https://raw.githubusercontent.com/JeffersonLab/alarms/main/classes
      ALARM_INSTANCES: https://raw.githubusercontent.com/JeffersonLab/alarms/main/instances/box