---
version: '3.8'

services:
  jaws:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CUSTOM_CRT_URL=http://pki.jlab.org/JLabCA.crt
    environment:
      TZ: "America/New_York"
      LOGLEVEL: "DEBUG"
      ALARM_LOCATIONS: /data/locations
      ALARM_CATEGORIES: /data/categories
      ALARM_CLASSES: /data/classes
      ALARM_INSTANCES: /data/instances
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - ./scripts:/scripts
      - ./examples/data:/data