services:
  kafka:
    extends:
      file: deps.yml
      service: kafka

  registry:
    extends:
      file: deps.yml
      service: registry

  jaws:
    tty: true
    stdin_open: true
    hostname: jaws
    container_name: jaws
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      TZ: "America/New_York"
      BOOTSTRAP_SERVERS: "kafka:9092"