services:
  epics2kafka:
    image: jeffersonlab/jaws-epics2kafka:${EPICS2KAFKA_VERSION}
    hostname: epics2kafka
    container_name: epics2kafka
    healthcheck:
      test: test $(/scripts/show-status.sh | grep RUNNING | wc -l) -eq 2
      start_period: 30s
      start_interval: 5s
      #      interval: 30s      # waiting for https://github.com/docker/compose/issues/10830
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      cli:
        condition: service_healthy
    ports:
      - 8083:8083
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONFIG_STORAGE_TOPIC=connect-configs
      - OFFSET_STORAGE_TOPIC=connect-offsets
      - STATUS_STORAGE_TOPIC=connect-status
    volumes:
      - ./container/epics2kafka/config:/config

  registrations2epics:
    image: jeffersonlab/jaws-registrations2epics:${REGISTRATIONS2EPICS_VERSION}
    hostname: registrations2epics
    container_name: registrations2epics
    healthcheck:
      test: test $(ps | grep jaws | wc -l) -gt 1
      start_period: 30s
      start_interval: 5s
      #      interval: 30s      # waiting for https://github.com/docker/compose/issues/10830
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      cli:
        condition: service_healthy
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY=http://registry:8081