services:
  zookeeper:
    extends:
      file: docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: docker-compose.yml
      service: kafka

  registry:
    extends:
      file: docker-compose.yml
      service: registry

  jaws:
    extends:
      file: docker-compose.yml
      service: jaws
    build:
      context: .
      dockerfile: Dockerfile
      target: tester
      args:
        - CUSTOM_CRT_URL=http://pki.jlab.org/JLabCA.crt
    environment:
      LOGLEVEL: "INFO"
      ALARM_LOCATIONS: ""
      ALARM_CATEGORIES: ""
      ALARM_CLASSES: ""
      ALARM_INSTANCES: ""
    volumes:
      - ./src/jaws_scripts:/opt/venv/lib/python3.9/site-packages/jaws_scripts
      - ./tests:/tests