services:
  zookeeper:
    extends:
      file: ../../deps.yml
      service: zookeeper

  kafka:
    extends:
      file: ../../deps.yml
      service: kafka

  registry:
    extends:
      file: ../../deps.yml
      service: registry

  effective:
    extends:
      file: effective.yml
      service: effective

  jaws:
    extends:
      file: effective.yml
      service: jaws

  admin:
    image: slominskir/jaws-admin-gui:1.3.0
    hostname: admin
    container_name: admin
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - jaws
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"