services:
  kafka:
    extends:
      file: ../../docker-compose.yml
      service: kafka

  registry:
    extends:
      file: ../../docker-compose.yml
      service: registry

  effective:
    extends:
      file: effective.yml
      service: effective

  jaws:
    extends:
      file: effective.yml
      service: jaws

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8082:8080"
      - "9991:9990"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_HOSTNAME: 'localhost'
      KEYCLOAK_FRONTEND_PORT: '8082'
      KEYCLOAK_SERVER_URL: 'http://keycloak:8080'
      KEYCLOAK_HOME: '/opt/keycloak'
      KEYCLOAK_REALM: 'test-realm'
      KEYCLOAK_RESOURCE: 'jaws'
      KEYCLOAK_SECRET: 'yHi6W2raPmLvPXoxqMA7VWbLAA2WN0eB'
      TZ: 'America/New_York'
    volumes:
      - ./keycloak:/scripts
    entrypoint: /scripts/docker-entrypoint.sh

  admin:
    image: jeffersonlab/jaws-admin-gui:4.5.0
    hostname: admin
    container_name: admin
    ports:
      - 8443:8443
      - 8080:8080
      - 9990:9990
    depends_on:
      - jaws
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY=http://registry:8081