services:
  kafka:
    extends:
      file: ../../docker-compose.yml
      service: kafka

  registry:
    extends:
      file: ../../docker-compose.yml
      service: registry

  effective:
    image: jeffersonlab/jaws-effective-processor:4.3.0
    hostname: effective
    container_name: effective
    depends_on:
      - jaws
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"

  jaws:
    extends:
      file: ../../docker-compose.yml
      service: jaws