services:
  zookeeper:
    extends:
      file: ../../deps.yml
      service: zookeeper

  kafka:
    extends:
      file: ../../deps.yml
      service: kafka

  registry:
    extends:
      file: ../../deps.yml
      service: registry

  effective:
    image: slominskir/jaws-effective-processor:4.2.0
    hostname: effective
    container_name: effective
    depends_on:
      - jaws
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"

  jaws:
    image: slominskir/jaws:4.5.3
    tty: true
    stdin_open: true
    hostname: jaws
    container_name: jaws
    depends_on:
      - registry
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"
      ALARM_LOCATIONS: https://raw.githubusercontent.com/JeffersonLab/alarms/main/locations
      ALARM_CATEGORIES: https://raw.githubusercontent.com/JeffersonLab/alarms/main/categories
      ALARM_CLASSES: https://raw.githubusercontent.com/JeffersonLab/alarms/main/classes
      ALARM_INSTANCES: https://raw.githubusercontent.com/JeffersonLab/alarms/main/instances/box