services:
  kafka:
    extends:
      file: ../../docker-compose.yml
      service: kafka

  registry:
    extends:
      file: ../../docker-compose.yml
      service: registry

  jaws:
    extends:
      file: ../../docker-compose.yml
      service: jaws

  softioc:
    image: jeffersonlab/softioc:1.1.0
    tty: true
    stdin_open: true
    hostname: softioc
    container_name: softioc
    ports:
      - "5064:5064/tcp"
      - "5065:5065/tcp"
      - "5064:5064/udp"
      - "5065:5065/udp"
    volumes:
      - ../softioc-db:/db

  epics2kafka:
    image: jeffersonlab/jaws-epics2kafka:4.6.0
    hostname: epics2kafka
    container_name: epics2kafka
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
    volumes:
      - ../connect-config:/config

  registrations2epics:
    image: jeffersonlab/registrations2epics:4.3.0
    hostname: registrations2epics
    container_name: registrations2epics
    depends_on:
      - kafka
      - registry
      - jaws
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY=http://registry:8081