name: GitHub Release

on:
  push:
    branches: [ main ]
    paths:
      - 'VERSION'
    tags-ignore:
      - '**'
  workflow_call:
    outputs:
      semvertag:
        description: "The semantic versioning tag name created"
        value: ${{ jobs.release.outputs.semvertag }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      semvertag: ${{ steps.getver.outputs.semvertag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read version file
        id: getver
        run: |
          . jaws-version.env
          echo "VERSION=v$JAWS_VERSION" >> $GITHUB_ENV
          echo "semvertag=v$JAWS_VERSION" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ env.VERSION }}